
export interface Service {
  id: string;
  title: string;
  description: string;
  icon: string; // URL or identifier
  imageUrl: string;
}

export interface Project {
  id: string;
  title: string;
  client: string;
  category: string;
  imageUrl: string;
  result: string; // e.g., "+150% Leads"
  description: string; // Full case study details
}

export interface NewsItem {
  id: string;
  title: string;
  category: string;
  summary: string;
  imageUrl: string;
  date: string;
  content?: string; // Optional full content
}

export interface TeamMember {
  id: string;
  name: string;
  role: string;
  imageUrl: string;
  bio: string;
}

// --- NEW TYPES FOR CRO & POSITIONING ---

export interface ClientPartner {
  id: string;
  name: string;
  logoUrl?: string; // Optional image URL, otherwise text
  sortOrder: number;
}

export interface ComparisonItem {
  id: string;
  criterion: string;
  duhavaValue: string; // "TRUE" for checkmark, or text
  agencyValue: string;
  freelanceValue: string;
  sortOrder: number;
}

export interface Persona {
  id: string;
  keyName: string; // 'STARTUP' | 'SME' | 'ENTERPRISE'
  title: string;
  description: string;
  focusTags: string[];
  ctaText: string;
  iconName: string;
}

export interface GalleryImage {
  id: string;
  imageUrl: string;
  caption?: string;
  sortOrder: number;
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  CLOSED = 'CLOSED',
  LOST = 'LOST'
}

export interface Lead {
  id?: string; // Optional for new leads (auto-generated by DB)
  name: string;
  email: string;
  phone: string;
  details: string;
  createdAt: string;
  status?: LeadStatus;
}

export enum AdminView {
  DASHBOARD = 'DASHBOARD',
  SERVICES = 'SERVICES',
  PROJECTS = 'PROJECTS',
  NEWS = 'NEWS',
  LEADS = 'LEADS',
  TEAM = 'TEAM',
  // New Views
  PARTNERS = 'PARTNERS',
  COMPARISON = 'COMPARISON',
  PERSONAS = 'PERSONAS',
  GALLERY = 'GALLERY'
}

export interface AlertState {
  show: boolean;
  message: string;
  type: 'success' | 'error';
}
